on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        # see https://github.com/marketplace/actions/arm-runner#cpu
        cpu: cortex-a7
        # see https://github.com/marketplace/actions/arm-runner#base_image
        base_image: raspios_lite_arm64:latest
        commands: |
           uname -a > /tmp/info.txt
        copy_artifact_path: /tmp/info.txt
    - name: Upload release image
      uses: actions/upload-artifact@v2
      with:
        name: Info
        path: info.txt
